// Minimal helper to serve modern formats generated by scripts/optimize-images.mjs.
// Works with Vite because outputs live in /public/optimized.

export function buildOptimizedSrcSet({
  basePath,
  widths = [480, 768, 1024, 1280],
  ext,
}) {
  // basePath: '/optimized/foo/bar' (no extension)
  // ext: 'webp' | 'avif'
  return widths.map((w) => `${basePath}-${w}w.${ext} ${w}w`).join(", ");
}

export function OptimizedPicture({
  src,
  alt,
  className,
  widths = [480, 768, 1024, 1280],
  sizes = "100vw",
  loading = "lazy",
  decoding = "async",
  fetchPriority,
  width,
  height,
  style,
}) {
  // src is the ORIGINAL asset path like '/assets/css1.jpg'
  // We rewrite to '/optimized/css1' (strip extension).
  const dot = src.lastIndexOf(".");
  const base = dot >= 0 ? src.slice(0, dot) : src;
  const optimizedBase = base.startsWith("/assets/")
    ? `/optimized${base.slice("/assets".length)}`
    : `/optimized${base.startsWith("/") ? base : `/${base}`}`;

  const avifSrcSet = buildOptimizedSrcSet({
    basePath: optimizedBase,
    widths,
    ext: "avif",
  });
  const webpSrcSet = buildOptimizedSrcSet({
    basePath: optimizedBase,
    widths,
    ext: "webp",
  });

  // Fallback: largest webp.
  const fallback = `${optimizedBase}-${Math.max(...widths)}w.webp`;

  return (
    <picture>
      <source type="image/avif" srcSet={avifSrcSet} sizes={sizes} />
      <source type="image/webp" srcSet={webpSrcSet} sizes={sizes} />
      <img
        src={fallback}
        alt={alt}
        className={className}
        loading={loading}
        decoding={decoding}
        fetchPriority={fetchPriority}
        width={width}
        height={height}
        style={style}
      />
    </picture>
  );
}
