export function OptimizedPicture({
  src,
  alt,
  className,
  widths = [480, 768, 1024, 1280],
  sizes = "100vw",
  loading = "lazy",
  decoding = "async",
  fetchPriority,
  width,
  height,
  style,
}) {
  // Keep srcsets aligned with what scripts/optimize-images.mjs actually writes.
  // That script generates multi-size variants only for these widths.
  const SUPPORTED_WIDTHS = [480, 768, 1024, 1280];

  // Minimal helper to serve modern formats generated by scripts/optimize-images.mjs.
  // Outputs live in /public/optimized so they are served as static assets.
  const buildOptimizedSrcSet = ({ basePath, widths, ext }) => {
    // Our optimizer writes suffixed files (e.g. -480w) for responsive variants.
    // Even when we only include a single width, we still need the suffix to
    // match the generated filenames.
    const useSuffix = true;
    return widths
      .map((w) => `${basePath}${useSuffix ? `-${w}w` : ""}.${ext} ${w}w`)
      .join(", ");
  };

  const normalizedWidths = Array.isArray(widths) ? widths : [widths];
  const filteredWidths = normalizedWidths
    .filter((w) => SUPPORTED_WIDTHS.includes(w))
    .sort((a, b) => a - b);

  // If the caller asked for only tiny widths (e.g. 120/240) we still want a
  // valid srcset that points to existing files. Use the smallest supported
  // width as a single-entry srcset.
  const effectiveWidths =
    filteredWidths.length > 0 ? filteredWidths : [SUPPORTED_WIDTHS[0]];

  // src is the ORIGINAL asset path like '/assets/screenshots/foo.png'
  // We rewrite to '/optimized/screenshots/foo' (strip extension).
  const dot = src.lastIndexOf(".");
  const base = dot >= 0 ? src.slice(0, dot) : src;

  const optimizedBase = base.startsWith("/assets/")
    ? `/optimized${base.slice("/assets".length)}`
    : `/optimized${base.startsWith("/") ? base : `/${base}`}`;

  const avifSrcSet = buildOptimizedSrcSet({
    basePath: optimizedBase,
    widths: effectiveWidths,
    ext: "avif",
  });
  const webpSrcSet = buildOptimizedSrcSet({
    basePath: optimizedBase,
    widths: effectiveWidths,
    ext: "webp",
  });

  // Use the original asset as the fallback `img src`. That guarantees we never
  // show a broken image if an optimized file is missing for any reason.
  const fallback = src;

  return (
    <picture>
      <source type="image/avif" srcSet={avifSrcSet} sizes={sizes} />
      <source type="image/webp" srcSet={webpSrcSet} sizes={sizes} />
      <img
        src={fallback}
        alt={alt}
        className={className}
        loading={loading}
        decoding={decoding}
        fetchPriority={fetchPriority}
        width={width}
        height={height}
        style={style}
      />
    </picture>
  );
}
